// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApplicationController from "./application_controller"
application.register("application", ApplicationController)

import CountriesSelectController from "./countries_select_controller"
application.register("countries-select", CountriesSelectController)

import CountryController from "./country_controller"
application.register("country", CountryController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)
